// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfzlalckxzmfdxrpnirg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmemxhbGNreHptZmR4cnBuaXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjY3NTcsImV4cCI6MjA2NzA0Mjc1N30.ti_GbZoTUTm9urJ9RvtcPtDKt7U0Ca6EBh47ACs25nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});